apiVersion: v1
kind: Service
metadata:
  name: blog-metrics-api
  namespace: peripherals
  labels:
    app: blog-metrics-api
    part-of: kautilya-pro-site
spec:
  selector:
    app: blog-metrics-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
